### ISSUE TITLE
html/cssls setup. Some idea with this pls?

### ISSUE THREAD

**Issue by sssimxn** [neovim/nvim-lspconfig#1160] opened 2021-08-18 19:18 UTC
I followed the steps of the [CONFIG.md](https://github.com/neovim/nvim-lspconfig/blob/master/CONFIG.md) to configure [html](https://github.com/neovim/nvim-lspconfig/blob/master/CONFIG.md#html) and [cssls](https://github.com/neovim/nvim-lspconfig/blob/master/CONFIG.md#cssls) but I get these errors, I tried some things and it keeps persisting

I don't have a lot of time that I use neovim and lsp, maybe it is a newbie mistake but I would be totally grateful if someone can help me, thanks in advance

*Translation: An error occurred while processing Auto-commands for "css" / "html"*
[![image](https://user-images.githubusercontent.com/62354548/129950503-4e0b38be-507c-4c92-b539-b202c651caf0.png)](url)
[![image](https://user-images.githubusercontent.com/62354548/129950702-946dedde-ca1b-4404-97f9-04588e0de515.png)](url)

Also when I run `:LspInfo` this is that I get
![image](https://user-images.githubusercontent.com/62354548/129958494-c3d30bd9-9204-4ae2-a8fc-7a6a3899eb27.png)

- `nvim --version`: NVIM v0.6.0-dev+43-g02bf251bb
- Operating system/version: Windows 10

### Code sample
My: `init.vim`
```vim
" LSP
Plug 'neovim/nvim-lspconfig'
Plug 'nvim-lua/completion-nvim'
" ;-;
Plug 'hrsh7th/vim-vsnip'
Plug 'hrsh7th/vim-vsnip-integ'

source $LOCALAPPDATA\nvim\config\lsp-config.vim
```
My: `lsp-config.vim`
```vim
lua << EOF
local nvim_lsp = require'lspconfig'

local capabilities = vim.lsp.protocol.make_client_capabilities()
capabilities.textDocument.completion.completionItem.snippetSupport = true

nvim_lsp.cssls.setup {
   on_attach = require'completion'.on_attach,
   capabilities = capabilities,
}
nvim_lsp.html.setup {
   on_attach = require'completion'.on_attach,
   capabilities = capabilities,
}
EOF
```

### Health check
<details>
<summary>Checkhealth result</summary>
health#lspconfig#check
======================================================================== <br>
## Checking language server protocol configuration <br>
  - INFO: cssls: configuration checked. <br>
  - INFO: html: configuration checked. <br>
  - INFO: tsserver: configuration checked.
</details>

**Comment by lithammer** [comment] 2021-08-18 19:24
Sounds like you haven installed [vscode-langservers-extracted](https://github.com/hrsh7th/vscode-langservers-extracted). Or they're not in your `PATH`.

**Comment by mjlbach** [comment] 2021-08-19 15:52
You can debug with this container https://github.com/mjlbach/lsp-containers/tree/master/htmlls

**Comment by mjlbach** [comment] 2021-08-21 12:17
I'm closing this as a usage/configuration question. Feel free to follow-up on our [discourse][[https://neovim.discourse.group/c/7-category/7] if you are still having issues debugging your config, but I'm not able to reproduce this in the container.

**Closed by mjlbach** 2021-08-21 12:17 UTC
Labels: bug
