### ISSUE TITLE
Volta Unable to find executable

### ISSUE THREAD

**Issue by AvlKP-dev** [neovim/nvim-lspconfig#1444] opened 2021-11-18 14:58 UTC
### Description

LspInfo is showing "Unable to find executable" for every server installed through Volta npm.
I noticed both cmd are suffixed with .cmd, while my other LSP that's working are not.
I tried to remove .cmd from the cmd, and it no longer throws the error. However, the LSP is now not working as expected (no syntax highlighting and others).
With some searching, I found out that .cmd is needed on Windows.

### Neovim version

NVIM v0.5.1
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3

### Operating system and version

Windows 10

### Affected language servers

svelte, tsserver

### Steps to reproduce

1. Install LSP according to readme
2. Open .svelte or .ts file
3. View LspInfo

### Actual behavior

Unable to find the executable of language server.

### Expected behavior

Language server functioning properly.

### Minimal config

```Lua
local on_windows = vim.loop.os_uname().version:match 'Windows'

local function join_paths(...)
  local path_sep = on_windows and '\\' or '/'
  local result = table.concat({ ... }, path_sep)
  return result
end

vim.cmd [[set runtimepath=$VIMRUNTIME]]

local temp_dir
if on_windows then
  temp_dir = vim.loop.os_getenv 'TEMP'
else
  temp_dir = '/tmp'
end

vim.cmd('set packpath=' .. join_paths(temp_dir, 'nvim', 'site'))

local package_root = join_paths(temp_dir, 'nvim', 'site', 'pack')
local install_path = join_paths(package_root, 'packer', 'start', 'packer.nvim')
local compile_path = join_paths(install_path, 'plugin', 'packer_compiled.lua')

local function load_plugins()
  require('packer').startup {
    {
      'wbthomason/packer.nvim',
      'neovim/nvim-lspconfig',
    },
    config = {
      package_root = package_root,
      compile_path = compile_path,
    },
  }
end

_G.load_config = function()
  vim.lsp.set_log_level 'trace'
  if vim.fn.has 'nvim-0.5.1' == 1 then
    require('vim.lsp.log').set_format_func(vim.inspect)
  end
  local nvim_lsp = require 'lspconfig'
  local on_attach = function(_, bufnr)
    local function buf_set_keymap(...)
      vim.api.nvim_buf_set_keymap(bufnr, ...)
    end
    local function buf_set_option(...)
      vim.api.nvim_buf_set_option(bufnr, ...)
    end

    buf_set_option('omnifunc', 'v:lua.vim.lsp.omnifunc')

    -- Mappings.
    local opts = { noremap = true, silent = true }
    buf_set_keymap('n', 'gD', '<Cmd>lua vim.lsp.buf.declaration()<CR>', opts)
    buf_set_keymap('n', 'gd', '<Cmd>lua vim.lsp.buf.definition()<CR>', opts)
    buf_set_keymap('n', 'K', '<Cmd>lua vim.lsp.buf.hover()<CR>', opts)
    buf_set_keymap('n', 'gi', '<cmd>lua vim.lsp.buf.implementation()<CR>', opts)
    buf_set_keymap('n', '<C-k>', '<cmd>lua vim.lsp.buf.signature_help()<CR>', opts)
    buf_set_keymap('n', '<space>wa', '<cmd>lua vim.lsp.buf.add_workspace_folder()<CR>', opts)
    buf_set_keymap('n', '<space>wr', '<cmd>lua vim.lsp.buf.remove_workspace_folder()<CR>', opts)
    buf_set_keymap('n', '<space>wl', '<cmd>lua print(vim.inspect(vim.lsp.buf.list_workspace_folders()))<CR>', opts)
    buf_set_keymap('n', '<space>D', '<cmd>lua vim.lsp.buf.type_definition()<CR>', opts)
    buf_set_keymap('n', '<space>rn', '<cmd>lua vim.lsp.buf.rename()<CR>', opts)
    buf_set_keymap('n', 'gr', '<cmd>lua vim.lsp.buf.references()<CR>', opts)
    buf_set_keymap('n', '<space>e', '<cmd>lua vim.lsp.diagnostic.show_line_diagnostics()<CR>', opts)
    buf_set_keymap('n', '[d', '<cmd>lua vim.lsp.diagnostic.goto_prev()<CR>', opts)
    buf_set_keymap('n', ']d', '<cmd>lua vim.lsp.diagnostic.goto_next()<CR>', opts)
    buf_set_keymap('n', '<space>q', '<cmd>lua vim.lsp.diagnostic.set_loclist()<CR>', opts)
  end

  -- Add the server that troubles you here
  local name = 'svelte'
  local cmd = { 'svelteserver.cmd', '--stdio' } -- needed for elixirls, omnisharp, sumneko_lua
  if not name then
    print 'You have not defined a server name, please edit minimal_init.lua'
  end
  if not nvim_lsp[name].document_config.default_config.cmd and not cmd then
    print [[You have not defined a server default cmd for a server
      that requires it please edit minimal_init.lua]]
  end

  nvim_lsp[name].setup {
    cmd = cmd,
    on_attach = on_attach,
  }

  print [[You can find your log at $HOME/.cache/nvim/lsp.log. Please paste in a github issue under a details tag as described in the issue template.]]
end

if vim.fn.isdirectory(install_path) == 0 then
  vim.fn.system { 'git', 'clone', 'https://github.com/wbthomason/packer.nvim', install_path }
  load_plugins()
  require('packer').sync()
  vim.cmd [[autocmd User PackerComplete ++once lua load_config()]]
else
  load_plugins()
  require('packer').sync()
  _G.load_config()
end
```

### Health check

health#lspconfig#check
========================================================================
## Checking language server protocol configuration
  - ERROR: svelte: The given command "svelteserver.cmd" is not executable.

### LSP log

https://gist.github.com/AvlKP-dev/54b35cab3cbe7ef5dbe0e77c52932198

**Comment by AvlKP-dev** [comment] 2021-11-18 15:51
Sorry, probably copied the thing before editing.
Fixed it.

**Comment by mjlbach** [comment] 2021-11-18 15:52
You installed the servers and both are executable from the command line?

**Comment by AvlKP-dev** [comment] 2021-11-18 16:23
Yes. Here is my installed packages (I'm using Volta):

⚡️ Currently active tools:

    Node: v14.17.6 (default)
    npm: v8.1.2 (default)
    Tool binaries available:
        tailwindcss-language-server (default)
        volar-server (default)
        emmet-ls (default)
        firebase (default)
        neovim-node-host (default)
        pyright, pyright-langserver (default)
        svelteserver (default)
        tsc, tsserver (current @ E:\Projects\Indput\package.json)
        typescript-language-server (default)
        vscode-css-language-server, vscode-eslint-language-server, vscode-html-language-server,
    vscode-
        json-language-server (default)

See options for more detailed reports by running `volta list --help`.

**Comment by mjlbach** [comment] 2021-11-18 16:25
Is the only issue you are having svelte? I was confused by your original issue which mentioned tsserver.

**Comment by AvlKP-dev** [comment] 2021-11-18 23:47
I have also experienced issue with tsserver, but decided to exclude it from the minimal config. Should I add it?

**Comment by AvlKP-dev** [comment] 2021-11-19 08:27
I have found the cause.  Volta automatically added the installed packages to a bin folder and the env variable is configured for that folder. The only bins in that folder are those without file extensions and a symbolic link .exe file. Is there any way to go around this?

**Comment by mjlbach** [comment] 2021-11-19 12:59
Well, you can try changing cmd to call insert_server_name.exe

I use Volta on linux/MacOS and the default configurations work fine. I’d have to find/look into this on windows
________________________________

**Comment by AvlKP-dev** [comment] 2021-11-19 13:01
I have done so, it still doesn't work for me. Installing it through nvim-lsp-installer fixed it for now.

**Comment by kylo252** [comment] 2021-11-20 11:15
Make sure that `:where svelteserver` actually works, and then just use:
```lua
require("lspconfig").svelte.setup({
  cmd = {
  "svelteserver",
   "--stdio"}
})
```

Otherwise, provide the full path to wherever `volta` has these binaries. 
 
Note: I was unable to use `"$env:LOCALAPPDATA\\Volta\\bin\\svelteserver.exe"` since Neovim was refusing to expand the environment variables, no matter what I tried.

**Comment by mjlbach** [comment] 2021-11-27 21:46
@williamboman I don't know what to do here. I think volta's installation is actually preferable because the installed packages are invokable without special casing the cmd name on windows... I could make it *not* special case the cmd on windows and then suggest people use volta to install. I'm not a windows user so I don't know the most convenient thing to do for them.

**Comment by mjlbach** [comment] 2021-11-27 21:47
@williamboman I don't know what to do here. I think volta's installation is actually preferable because the installed packages are invokable without special casing the cmd name on windows... I could make it *not* special case the cmd on windows and then suggest people use volta to install. I'm not a windows user so I don't know the most convenient thing to do for them.

**Comment by williamboman** [comment] 2021-11-28 00:20
Hm I'm not familiar with this problem (I am mostly improvising with most things Windows). Would it be possible to try to detect what flavour of Node/npm installation is active based on some heuristics and use that to modify the cmd accordingly?

**Comment by mjlbach** [comment] 2021-11-28 01:58
I would rather not introduce complexity to deal with windows. The problem is actually already an issue sans volta, many commands implement the post-hoc postfixing with `.cmd` for windows. I am contemplating dropping it entirely and encouraging windows users to use volta, but that might entail nvim-lsp-install adding the shims to call the language server without the post-fixed `.cmd`

**Comment by mjlbach** [comment] 2021-11-28 22:09
I know the issue now. Closing this issue in favor of #1500

**Closed by mjlbach** 2021-11-28 22:09 UTC
Labels: bug
