### ISSUE TITLE
Sumneko Lua some docs too large

### ISSUE THREAD

**Issue by jacksonludwig** [neovim/nvim-lspconfig#484] opened 2020-12-23 15:45 UTC
- `nvim --version`: NVIM v0.5.0-dev+965-gd0668b36a
- nvim-lsp version(commit hash): dbc4bf514198f9e328e200a9aa63b462d6e1e9f1
- `:checkhealth` result: all green/checks for installed servers
- What language server(If the problem is related to a specific language server): sumneko_lua
- Operating system/version: Ubuntu (also occurs on arch)
- Terminal name/version: Windows terminal (also occurs on alacritty)
- `$TERM`: xterm-256color

### How to reproduce the problem from neovim startup
Go to a lua file with the sumneko_lua server active.
Trigger ``lua vim.lsp.buf.hover()`` for a function like ``print()``.

### Actual behaviour
Doc has a lot of empty space and extends to end of the screen.
![image](https://user-images.githubusercontent.com/42984254/103013892-e2fb2a00-450b-11eb-8e47-13b9a99ad77a.png)

### Expected behaviour
Doc should have less empty space and be longer vertically.

**Comment by mjlbach** [comment] 2020-12-24 02:30
I think this is an upstream issue. Can you reproduce on another language client?

**Comment by ludwj61** [comment] 2020-12-24 04:16
Using coc with this LSP does not have this issue exactly, although the docs do not look great with that as well; they have some junk text and some blank areas as well (although not this severe). 

So since they both have some issues, you're probably right that it's the server's fault for providing docs in a weird way.

**Comment by mjlbach** [comment] 2020-12-30 00:00
Closing as upstream. If there's an initialization option we should be setting, then feel free to reopen. Otherwise I recommend filing upstream with the documentation you've shown for both coc and nvim's lsc.

**Closed by mjlbach** 2020-12-30 00:00 UTC
Labels: bug
