### ISSUE TITLE
lua-language-server:  wrong cmd on Windows

### ISSUE THREAD

**Issue by xarthurx** [neovim/nvim-lspconfig#2032] opened 2022-07-27 12:07 UTC
### Description

On Windows, when using https://github.com/sumneko/lua-language-server, it always show the following error when opening a `.lua` file:
![image](https://user-images.githubusercontent.com/1921878/181241995-6cc65a31-2fec-4202-8953-e8cd84274df9.png)

After digging, it turns out that the correct name should be `lua-language-server.cmd` instead of `lua-language-server`:
![image](https://user-images.githubusercontent.com/1921878/181242139-bfdef1dd-7bf5-41a1-a803-dd283cbc56cf.png)

I think `lspconfig` should generate platform-based `cmd` for this package.

### Neovim version

Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3
Compiled by runneradmin@fv-az276-503

### Operating system and version

Windows 11 + PowerShell

### Affected language servers

lua-language-server

### Steps to reproduce

1. open `nvim`
2. open a `.lua` file

### Actual behavior

`lua-language-server` cannot be found.

### Expected behavior

`lua-language-server` should be found and used.

### Minimal config

```Lua
below.
```

### LSP log

https://gist.github.com/xarthurx/262a5feba8f14cc0da55400d981552ca

**Comment by justinmk** [comment] 2022-07-27 13:37
similar to https://github.com/neovim/nvim-lspconfig/pull/2013

**Comment by williamboman** [comment] 2022-07-31 12:19
@xarthurx Do you happen to use mason.nvim? It will write `.cmd` executable shims on Windows systems, which doesn't play nicely with libuv (which Neovim's LSP client uses to spawn servers). If you download `lua-language-server` directly from their GitHub releases, you'll get an `.exe`, which will work fine. [mason-lspconfig.nvim](https://github.com/williamboman/mason-lspconfig.nvim) fixes these inconsistencies and is strongly recommended for Windows users.

The problem is with how libuv doesn't recognize `.cmd` (or `.bat`) executables in `PATH` on Windows regardless of how `PATHEXT` is configured (the reason is `CreateProcess can start only .com and .exe files, only those extensions are tried.`). 

`exepath()` seems to solve this pretty nicely, as Neovim [does respect `PATHEXT`](https://github.com/neovim/neovim/blob/9511faa819e8260aa7ae2c2ff140070bbc96efa9/src/nvim/os/fs.c#L321-L324). [null-ls uses it](https://github.com/jose-elias-alvarez/null-ls.nvim/blob/47c04991af80b6acdf08a5db057908b52f4d0699/lua/null-ls/loop.lua#L147) and [mason-lspconfig.nvim successfully patches cmds with it](https://github.com/williamboman/mason-lspconfig.nvim/blob/f87c5796603aa3436d9cb1d36dbe5b2e579e4034/lua/mason-lspconfig/lspconfig_hook.lua#L66-L69). I'd be happy to open a PR that patches commands with `exepath()` on Windows + normalizes all commands in server configs.

**Comment by xarthurx** [comment] 2022-08-01 12:33
@williamboman 

That’ll be super helpful to patch the command.
If I can help with anything, plz let me know.

**Comment by justinmk** [comment] 2022-08-01 12:37
> `exepath()` seems to solve this pretty nicely, as Neovim [does respect `PATHEXT`](https://github.com/neovim/neovim/blob/9511faa819e8260aa7ae2c2ff140070bbc96efa9/src/nvim/os/fs.c#L321-L324). [null-ls uses it](https://github.com/jose-elias-alvarez/null-ls.nvim/blob/47c04991af80b6acdf08a5db057908b52f4d0699/lua/null-ls/loop.lua#L147) and [mason-lspconfig.nvim successfully patches cmds with it](https://github.com/williamboman/mason-lspconfig.nvim/blob/f87c5796603aa3436d9cb1d36dbe5b2e579e4034/lua/mason-lspconfig/lspconfig_hook.lua#L66-L69). I'd be happy to open a PR that patches commands with `exepath()` on Windows + normalizes all commands in server configs.

That sounds like a good idea. Might want to check the git logs / PRs to see if there was a reason that uv_spawn was used directly. I'm wondering myself why we don't use e.g. `vim.fn.system()` (exepath() also would work).

**Comment by justinmk** [comment] 2022-09-11 18:43
closed by https://github.com/neovim/nvim-lspconfig/pull/2039

but I have opened https://github.com/neovim/nvim-lspconfig/issues/2130 to track the general solution

**Closed by justinmk** 2022-09-11 18:43 UTC
Labels: bug

**Comment by xarthurx** [comment] 2022-10-11 07:35
Yes, I use Manson.vim

That’ll be super helpful to patch the command.
If I can help with anything, plz let me know.
