### ISSUE TITLE
On_Attach not triggered

### ISSUE THREAD

**Issue by riez** [neovim/nvim-lspconfig#1381] opened 2021-11-07 05:55 UTC
### Description

Version: NVIM v0.5.1
Config location: $HOME/.config/nvim/after/plugin

on_attach function is not triggered even with client attach on LspInfo

![image](https://user-images.githubusercontent.com/37952353/140633457-7eae61e1-8838-4c55-92cd-ebf5ba972a3e.png)

### Neovim version

NVIM v0.5.1
Build type: Release
LuaJIT 2.1.0-beta3

### Operating system and version

macOs 12.0.1

### Affected language servers

all

### Steps to reproduce

1. Init language server
2. add on_attach simple function to print text
3. No text printed & when do `:LspInfo` client buffer attached successfully

### Actual behavior

The custom_attach is not triggered.

### Expected behavior

The custom_attach should be triggered and printing "work!"

### Minimal config

```Lua
if !exists('g:lspconfig')
  finish
endif

lua << EOF
local nvim_lsp = require('lspconfig')

local custom_attach = function(client, bufnr)
print("hhello")
end

nvim_lsp.pyright.setup{
on_attach = custom_attach
}
EOF
```
```


### Health check


health#lspconfig#check
========================================================================
## Checking language server protocol configuration
  - INFO: tsserver: configuration checked.
  - INFO: rust_analyzer: configuration checked.
  - INFO: tailwindcss: configuration checked.
  - INFO: vimls: configuration checked.
  - INFO: yamlls: configuration checked.
  - INFO: sumneko_lua: configuration checked.
  - INFO: vuels: configuration checked.
  - INFO: cssls: configuration checked.
  - INFO: html: configuration checked.
  - INFO: bashls: configuration checked.
  - INFO: dockerls: configuration checked.
  - INFO: pyright: configuration checked.
  - INFO: flow: configuration checked.
  - INFO: diagnosticls: configuration checked.
  - INFO: jsonls: configuration checked.
  - INFO: graphql: configuration checked.
  - INFO: intelephense: confguration checked.
  - INFO: kotlin_language_server: configuration checked.
  - INFO: eslint: configuration checked.
  - INFO: svelte: configuration checked.


### LSP log

https://gist.github.com/riez/9f33989e40e80e522caf0df2030312d9

**Comment by mjlbach** [comment] 2021-11-08 07:21
Can't reproduce, works fine on master (note, if you use nvim -u init.vim then MYVIMRC is unset)

```
" Bootstrap Plug
let autoload_plug_path = stdpath('data') . '/site/autoload/plug.vim'
if !filereadable(autoload_plug_path)
  silent execute '!curl -fLo ' . autoload_plug_path . '  --create-dirs 
      \ "https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim"'
  autocmd VimEnter * PlugInstall --sync | source $MYVIMRC
endif
unlet autoload_plug_path

call plug#begin(stdpath('data') . '/plugged')


Plug 'neovim/nvim-lspconfig'

call plug#end()

lua << EOF
local nvim_lsp = require('lspconfig')

local custom_attach = function(client, bufnr)
print("hello")
end

nvim_lsp.pyright.setup{
on_attach = custom_attach
}
EOF
```

**Comment by mjlbach** [comment] 2021-11-09 18:15
Closing, I can't reproduce in an ubuntu 18.04 container either. Check your plugins (move ~/.local/share/site) and your runtime files.

**Closed by mjlbach** 2021-11-09 18:15 UTC
Labels: bug

**Comment by riez** [comment] 2021-11-10 13:45
You were right! I was dumb, the nvm-lsp-installer config overriding the setup ... Thanks man..

**Comment by jonsmithers** [comment] 2021-11-28 18:20
Could there be a warning when re-invoking setup? I copy-pasted basic configuration from nvim-lspconfig and nvim-cmp. They both invoked `setup`, thus causing this situation.

https://github.com/hrsh7th/nvim-cmp/blob/092fb66b6ddb4b12b9b542d105d7af40e4fbd9f2/README.md?plain=1#L123-L128

https://github.com/neovim/nvim-lspconfig/blob/d9aa848da3905e0f8153e546d7b630d3d13e0435/README.md?plain=1#L129-L140

**Comment by Small-Sheep-nice** [comment] 2023-03-02 11:37
Thank you!
