### ISSUE TITLE
When customizing root_dir, buffer names end-up being absolute, but only in pyright

### ISSUE THREAD

**Issue by fsouza** [neovim/nvim-lspconfig#1851] opened 2022-04-24 01:58 UTC
### Description

This is _very_ weird, opening here because I'm looking for ideas on how to debug this. Also I'm not sure if this should be here or in neovim/neovim, but starting here.

I noticed that when I customize the `root_dir` function, the buffer names for files end-up being absolute paths, but only for files attached to pyright (!), and not on the first file I open.

I'm doing something very simple for the root_dir customization:

```lua
  root_dir = function()
    return vim.fn.getcwd()
  end,
```

To be fair, everything works, it's just annoying :) I have considered the classic `cd .` in an autocmd to force relative paths, but I'm curious if anyone has any clues on what could be going on.

### Neovim version

NVIM v0.8.0-dev+41-g6d0915536

### Nvim-lspconfig version

ad9903c66bac88f344890acb6532f63f1cd4dac3

### Operating system and version

macOS 12.3.1

### Affected language servers

pyright

### Steps to reproduce

In some repo that has python files (for example, autoflake8):

1. `nvim -u minimal.lua autoflake8/cli.py`
2. inside neovim:
2.a `:echo bufname()` -- prints autoflake8/cli.py
2.b `:edit autoflake8/pending_fix.py`
2.c `:echo bufname()` -- prints absolte path

Can also reproduce without starting from the file:

1. `nvim -u minimal.lua`
2. inside neovim:
2.a `:edit autoflake8/cli.py`
2.b `:echo bufname()` -- prints autoflake8/cli.py
2.c `:edit autoflake8/pending_fix.py`
2.d `:echo bufname()` -- prints absolte path

Notice that this does not happen with Go and gopls. Using a repo with Go files (for example, fake-gcs-server):

1. `nvim -u minimal.lua fakestorage/object.go`
2. inside neovim:
2.a `:echo bufname()` -- prints fakestorage/object.go
2.b `:edit internal/notification/event.go`
2.c `:echo bufname()` -- prints internal/notification/event.go

If I comment the root_dir customization in minimal.lua, everything behaves as expected in pyright 🤔 

### Actual behavior

Buffers attached to pyright have absolute names (except for the first buffer that I open).

### Expected behavior

All buffers have relative names.

### Minimal config

```Lua
local on_windows = vim.loop.os_uname().version:match 'Windows'

local function join_paths(...)
  local path_sep = on_windows and '\\' or '/'
  local result = table.concat({ ... }, path_sep)
  return result
end

vim.cmd [[set runtimepath=$VIMRUNTIME]]

local temp_dir = vim.loop.os_getenv 'TEMP' or '/tmp'

vim.cmd('set packpath=' .. join_paths(temp_dir, 'nvim', 'site'))

local package_root = join_paths(temp_dir, 'nvim', 'site', 'pack')
local install_path = join_paths(package_root, 'packer', 'start', 'packer.nvim')
local compile_path = join_paths(install_path, 'plugin', 'packer_compiled.lua')

local function load_plugins()
  require('packer').startup {
    {
      'wbthomason/packer.nvim',
      'neovim/nvim-lspconfig',
    },
    config = {
      package_root = package_root,
      compile_path = compile_path,
    },
  }
end

_G.load_config = function()
  vim.o.background = 'light'
  vim.lsp.set_log_level 'trace'
  if vim.fn.has 'nvim-0.5.1' == 1 then
    require('vim.lsp.log').set_format_func(vim.inspect)
  end
  local nvim_lsp = require 'lspconfig'
  local on_attach = function(_, bufnr)
    local function buf_set_keymap(...)
      vim.api.nvim_buf_set_keymap(bufnr, ...)
    end
    local function buf_set_option(...)
      vim.api.nvim_buf_set_option(bufnr, ...)
    end

    buf_set_option('omnifunc', 'v:lua.vim.lsp.omnifunc')

    -- Mappings.
    local opts = { noremap = true, silent = true }
    buf_set_keymap('n', 'gD', '<Cmd>lua vim.lsp.buf.declaration()<CR>', opts)
    buf_set_keymap('n', 'gd', '<Cmd>lua vim.lsp.buf.definition()<CR>', opts)
    buf_set_keymap('n', 'K', '<Cmd>lua vim.lsp.buf.hover()<CR>', opts)
    buf_set_keymap('n', 'gi', '<cmd>lua vim.lsp.buf.implementation()<CR>', opts)
    buf_set_keymap('n', '<C-k>', '<cmd>lua vim.lsp.buf.signature_help()<CR>', opts)
    buf_set_keymap('n', '<space>wa', '<cmd>lua vim.lsp.buf.add_workspace_folder()<CR>', opts)
    buf_set_keymap('n', '<space>wr', '<cmd>lua vim.lsp.buf.remove_workspace_folder()<CR>', opts)
    buf_set_keymap('n', '<space>wl', '<cmd>lua print(vim.inspect(vim.lsp.buf.list_workspace_folders()))<CR>', opts)
    buf_set_keymap('n', '<space>D', '<cmd>lua vim.lsp.buf.type_definition()<CR>', opts)
    buf_set_keymap('n', '<space>rn', '<cmd>lua vim.lsp.buf.rename()<CR>', opts)
    buf_set_keymap('n', 'gr', '<cmd>lua vim.lsp.buf.references()<CR>', opts)
    buf_set_keymap('n', '<space>e', '<cmd>lua vim.lsp.diagnostic.show_line_diagnostics()<CR>', opts)
    buf_set_keymap('n', '[d', '<cmd>lua vim.lsp.diagnostic.goto_prev()<CR>', opts)
    buf_set_keymap('n', ']d', '<cmd>lua vim.lsp.diagnostic.goto_next()<CR>', opts)
    buf_set_keymap('n', '<space>q', '<cmd>lua vim.lsp.diagnostic.set_loclist()<CR>', opts)
  end

  local root_dir = function()
    return vim.fn.getcwd()
  end

  nvim_lsp['pyright'].setup {
    cmd = { 'npx', '-p', 'pyright', 'pyright-langserver', '--stdio' },
    on_attach = on_attach,
    root_dir = root_dir,
  }

  nvim_lsp['gopls'].setup {
    cmd = { 'go', 'run', 'golang.org/x/tools/gopls@latest' },
    on_attach = on_attach,
    root_dir = root_dir,
  }

  print [[You can find your log at $HOME/.cache/nvim/lsp.log. Please paste in a github issue under a details tag as described in the issue template.]]
end

if vim.fn.isdirectory(install_path) == 0 then
  vim.fn.system { 'git', 'clone', 'https://github.com/wbthomason/packer.nvim', install_path }
  load_plugins()
  require('packer').sync()
  vim.cmd [[autocmd User PackerComplete ++once lua load_config()]]
else
  load_plugins()
  require('packer').sync()
  _G.load_config()
end
```

### LSP log

https://gist.github.com/fsouza/db79b5222dff770d06319d5c595b6584

**Comment by mjlbach** [comment] 2022-04-25 14:49
This is probably a duplicate of https://github.com/neovim/nvim-lspconfig/issues/1829

**Comment by fsouza** [comment] 2022-04-25 15:02
Yeah I think that there are no guarantees, but the reason I decided to open an issue anyways are:

1. It only happens when I customize the `root_dir` function
2. It only happens with pyright

For now, I'm just running `cd .` on Python files to "fix" it, but I don't feel great about that and may end-up doing something else.

**Comment by nyngwang** [comment] 2022-05-18 18:15
I encountered a bug that might be related to this months ago: I also customized the `root_dir` and if I rename an already `import`ed module, pyright(or, nvim-lspconfig, not sure) won't be able to detect the new file. E.g.

```py
from mod import some_pkg

result = some_pkg.foo()
```

if you rename the module file `some_pkg.py` to whatever valid name, then you won't be able to see the method `.foo()` when typing `some_pkg.` (I'm using nvim-cmp for completion, but I don't think this bug is related to it.)

**Comment by fsouza** [comment] 2022-05-18 18:27
@nyngwang that's a different issue. That's due to neovim not supporting didChangeWatchedFiles, which is what pyright uses to understand that there's a new file/module and that the old one no longer exists. As far as I understand, this will be get implemented at some point (see https://github.com/neovim/neovim/pull/16214).

I implemented the feature in my dotfiles and thought about turning it into a plugin, but figured that if neovim will have it soon, I don't need to publish anything that will need to be archived later 😁

**Comment by nyngwang** [comment] 2022-05-18 18:34
Oops... Thanks for your info!

**Comment by glepnir** [comment] 2022-08-25 12:24
so we can close this issue right ? open on upstream then link to that pr.

**Closed by glepnir** 2022-08-25 12:24 UTC
Labels: bug
