### ISSUE TITLE
Lsp error, client instantly quits

### ISSUE THREAD

**Issue by xiqqsec** [neovim/nvim-lspconfig#2357] opened 2022-12-25 16:19 UTC
### Description

I am having issues with LSP in regards to rust.

Everytime I run neovim on my working directory it gives me this error:
`Client 1 quit with exit code 101 and signal 0`

Looking at my LSP logs, i also see this:

`[ERROR][2022-12-25 15:53:47] .../vim/lsp/rpc.lua:733	"rpc"	"rust-analyzer"	"stderr"	'[ERROR rust_analyzer] Unexpected error: expected Message::Notification, got: Notification(Notification { method: "workspace/didChangeWorkspaceFolders", params: Object {"event": Object {"removed": Array [Array []], "added": Array [Object {"uri": String("file:///home/user/Projects/redacted"), "name": String("/home/user/Projects/redacted")}]}} })\nexpected Message::Notification, got: Notification(Notification { method: "workspace/didChangeWorkspaceFolders", params: Object {"event": Object {"removed": Array [Array []], "added": Array [Object {"uri": String("file:///home/user/Projects/redacted"), "name": String("/home/user/Projects/redacted")}]}} })\n'`

### Neovim version

NVIM v0.8.1
Build type: Release
LuaJIT 2.1.0-beta3

### Operating system and version

Fedora 35

### Affected language servers

rust-analyzer

### Steps to reproduce

1. nvim example.rs

### Actual behavior

![error](https://user-images.githubusercontent.com/87322933/209474918-214a751c-489f-4ec7-8887-9f6799119490.png)

### Minimal config

```Lua
`local on_windows = vim.loop.os_uname().version:match 'Windows'

local function join_paths(...)
  local path_sep = on_windows and '\\' or '/'
  local result = table.concat({ ... }, path_sep)
  return result
end

vim.cmd [[set runtimepath=$VIMRUNTIME]]

local temp_dir = vim.loop.os_getenv 'TEMP' or '/tmp'

vim.cmd('set packpath=' .. join_paths(temp_dir, 'nvim', 'site'))

local package_root = join_paths(temp_dir, 'nvim', 'site', 'pack')
local lspconfig_path = join_paths(package_root, 'test', 'start', 'nvim-lspconfig')

if vim.fn.isdirectory(lspconfig_path) ~= 1 then
  vim.fn.system { 'git', 'clone', 'https://github.com/neovim/nvim-lspconfig', lspconfig_path }
end

vim.lsp.set_log_level 'trace'
require('vim.lsp.log').set_format_func(vim.inspect)
local nvim_lsp = require 'lspconfig'
local on_attach = function(_, bufnr)
  local function buf_set_option(...)
    vim.api.nvim_buf_set_option(bufnr, ...)
  end

  buf_set_option('omnifunc', 'v:lua.vim.lsp.omnifunc')

  -- Mappings.
  local opts = { buffer = bufnr, noremap = true, silent = true }
  vim.keymap.set('n', 'gD', vim.lsp.buf.declaration, opts)
  vim.keymap.set('n', 'gd', vim.lsp.buf.definition, opts)
  vim.keymap.set('n', 'K', vim.lsp.buf.hover, opts)
  vim.keymap.set('n', 'gi', vim.lsp.buf.implementation, opts)
  vim.keymap.set('n', '<C-k>', vim.lsp.buf.signature_help, opts)
  vim.keymap.set('n', '<space>wa', vim.lsp.buf.add_workspace_folder, opts)
  vim.keymap.set('n', '<space>wr', vim.lsp.buf.remove_workspace_folder, opts)
  vim.keymap.set('n', '<space>wl', function()
    print(vim.inspect(vim.lsp.buf.list_workspace_folders()))
  end, opts)
  vim.keymap.set('n', '<space>D', vim.lsp.buf.type_definition, opts)
  vim.keymap.set('n', '<space>rn', vim.lsp.buf.rename, opts)
  vim.keymap.set('n', 'gr', vim.lsp.buf.references, opts)
  vim.keymap.set('n', '<space>e', vim.diagnostic.open_float, opts)
  vim.keymap.set('n', '[d', vim.diagnostic.goto_prev, opts)
  vim.keymap.set('n', ']d', vim.diagnostic.goto_next, opts)
  vim.keymap.set('n', '<space>q', vim.diagnostic.setloclist, opts)
end

-- Add the server that troubles you here
local name = 'rust-analyzer'
local cmd = { 'rust-analyzer', '--stdio' } -- needed for elixirls, omnisharp, sumneko_lua
if not name then
  print 'You have not defined a server name, please edit minimal_init.lua'
end
if not nvim_lsp[name].document_config.default_config.cmd and not cmd then
  print [[You have not defined a server default cmd for a server
    that requires it please edit minimal_init.lua]]
end

local lsp_flags = {
  -- This is the default in Nvim 0.7+
  debounce_text_changes = 150,
}

nvim_lsp[name].setup {
    on_attach = on_attach,
    flags = lsp_flags,
    settings = {
        [name] = {
            checkOnSave = {
                command = "clippy"
            },
        }
    }
}

print [[You can find your log at $HOME/.cache/nvim/lsp.log. Please paste in a github issue under a details tag as described in the issue template.]]`
```

### LSP log

https://gist.github.com/xiqqsec/567a3561eeaca5082e2fab61e0c54591

**Comment by arsham** [comment] 2022-12-25 17:43
I can confirm this behaviour. It seems that it was introduced in 212b99bc12a5416df8b2a610711ba399e2fc388a.

**Comment by xiqqsec** [comment] 2022-12-25 18:23
> I can confirm this behaviour. It seems that it was introduced in [212b99b](https://github.com/neovim/nvim-lspconfig/commit/212b99bc12a5416df8b2a610711ba399e2fc388a).

yeah I was reading through some of the latest issues, I rolled back to a previous commit, as I saw someone mentioning it here https://github.com/neovim/nvim-lspconfig/issues/2355#issuecomment-1364693110

**Comment by theHamsta** [comment] 2022-12-26 01:04
Can confirm this with rust-analyzer. `212b99b~` would work, `212b99b` not.

**Comment by glepnir** [comment] 2022-12-26 04:12
can you test #2356 ?

**Comment by lvim-tech** [comment] 2022-12-26 04:28
@glepnir, lsp server starting, but have a problem - each buffer starting instance of rust-analyzer (#2356 )

**Comment by glepnir** [comment] 2022-12-26 04:56
the latest commit of that pr ? it only spawn one rust-analyzer in my test hmm

**Comment by lvim-tech** [comment] 2022-12-26 05:02
![Screenshot from 2022-12-26 07-01-34](https://user-images.githubusercontent.com/82431193/209503544-404ff5ba-84ae-40db-b0f3-3c7b6a8d13d7.png)

**Comment by glepnir** [comment] 2022-12-26 05:07
works for like this

![images](https://user-images.githubusercontent.com/41671631/209503899-dce65618-459f-4f4d-826b-e92b3aa2e01e.gif)

**Comment by lvim-tech** [comment] 2022-12-26 05:11
Try session with split

**Comment by lvim-tech** [comment] 2022-12-26 05:23
![Peek 2022-12-26 07-20](https://user-images.githubusercontent.com/82431193/209505734-df8607ed-7547-4713-8b54-446e49580c1e.gif)

**Comment by glepnir** [comment] 2022-12-26 05:23
@lvim-tech  fixed

**Comment by lvim-tech** [comment] 2022-12-26 05:26
Tested, work!

**Comment by glepnir** [comment] 2022-12-26 12:45
> when switching between two projects, the lsp server is duplicated

@lvim-tech  a reproduce step ?

**Comment by lvim-tech** [comment] 2022-12-26 13:41
@glepnir, This problem is only for sumneko lsp. With another server it works fine. Maybe the problem is mine. You can close this issue. Thanks!

**Comment by somnam** [comment] 2022-12-26 20:45
@glepnir : The original problem contains an issue that I think was overlooked - the `removed` attribute of `WorkspaceFoldersChangeEvent` object is incorrectly generated on lua side as a list containing an empty list:
```lua
    local params = lsp.util.make_workspace_params(
      { { uri = vim.uri_from_fname(root_dir), name = root_dir } }, -- added
      { {} }  -- removed
    )
```

The error log posted by @xiqqsec  shows this value on lsp side: `"removed": Array [Array []]`
This caused a similar lsp server error for me using `jedi-language-server` - after opening a python file and running `e!` on the file i got:
`LSP[jedi_language_server] Unexpected error in LSP server, see server's logs for details`  
And an eror in the lsp server:
```
  |     res['removed'] = __c_structure_removed(o['removed'], __c_type_removed)                                    
  |                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^                                   
  |     raise IterableValidationError(                                                                            
  | cattrs.errors.IterableValidationError: While structuring typing.List[lsprotocol.types.WorkspaceFolder] (1 sub-exception)
```

Which lead me to https://github.com/microsoft/lsprotocol/blob/main/lsprotocol/types.py#L5373
```python
    removed: List[WorkspaceFolder] = attrs.field()
    """The array of the removed workspace folders."""
```
and the original spec: [workspace_didChangeWorkspaceFolders](https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#workspace_didChangeWorkspaceFolders).

The fix looks trivial, just to set removed as `{}`.

**Comment by glepnir** [comment] 2022-12-27 02:16
@somnam  right . I also found same thing in log in rust-anaylazyer .

**Closed** 2022-12-27 03:59 UTC
Labels: bug
