### ISSUE TITLE
LspInfo error

### ISSUE THREAD

**Issue by GustavoPrietoP** [neovim/nvim-lspconfig#828] opened 2021-04-08 12:07 UTC
![error](https://user-images.githubusercontent.com/70907734/114023687-2cfce700-9841-11eb-8452-cc235911c2dc.png)

Hey, I keep on getting this erorr whenever i type `:LspInfo` and i haven't found anything related to the same issue.

**Comment by lithammer** [comment] 2021-04-08 12:09
Duplicate of https://github.com/neovim/nvim-lspconfig/issues/827

**Closed** 2021-04-08 12:12 UTC
Labels: bug
