### ISSUE TITLE
rust_analyzer skip root_dirs for external crates inside `~/.cargo`

### ISSUE THREAD

**Issue by ten3roberts** [neovim/nvim-lspconfig#2518] opened 2023-03-20 10:58 UTC
### Language server

rust_analyzer

### Requested feature

In VSCode, external crates are skipped and not added to the `workspace_folders`.

This is not the case for the root_dir function in lsp-config.

The consequence is that using `goto definition` on a symbol which takes you to source code in `~/.cargo/registry/src/...` the external crate is added and rust-analyzer will then run `cargo check` or `cargo clippy` inside that folder as well, which will cause diagnostics from those crates to show up in workspace diagnostics.

This results in both increased time for producing diagnostics and other linting when saving, as RA has to check more, as well as cluttering the results of workspace diagnostics with warnings from other crates or the standard library, which are plentiful.

Relevant solution, which doesn't work with cargo workspaces as it uses a completely different root pattern resolution than the built in one: https://users.rust-lang.org/t/neovim-lsp-shows-diagnostic-for-external-crates/89842/3

**Comment by glepnir** [comment] 2023-03-20 11:08
as far as i know `rust_analyzer`  does not support lsp `workspace_folders` . you mean vscode workspace?

**Comment by glepnir** [comment] 2023-03-20 12:54
it just passed root dir into it.the rust analyzer not support lsp workspace relate features

**Comment by last-partizan** [comment] 2023-05-03 07:38
Same problem with `pyright`.

When i use `goto definition` to look for some dependency code, i end up with my workspace diagnostics full of `venv` error messages.

**Comment by ten3roberts** [comment] 2023-05-03 08:20
Do you know why VSCode doesn't experience this issue?

**Comment by ten3roberts** [comment] 2023-05-03 09:34
That is one solution, but prevents goto definition when looking inside a dependency, which vs code supports still

**Comment by glepnir** [comment] 2023-05-03 09:51
does vscode spawn two rust_analyzer process or only reuse one ?

**Comment by last-partizan** [comment] 2023-05-03 10:23
When i open definition in vscode, it displays problems for that file.

![image](https://user-images.githubusercontent.com/301015/235890162-146a0a4b-5f58-480e-bc6e-e8dabf11337d.png)

But when i close that tab, problem list is cleared.
![image](https://user-images.githubusercontent.com/301015/235890295-658f9e35-06a8-468b-8b29-66744ca6ce80.png)

It works with single pylance server running:

```
ps ax | grep -E '[p]ylance'
  89076 ?        Sl     0:16 /usr/lib/electron19/electron /home/serg/.vscode-oss/extensions/ms-python.vscode-pylance-2023.4.40/dist/server.bundle.js --cancellationReceive=file:2340df95b645411d81926a21616e9597105d30da0e --node-ipc --clientProcessId=89000
```

In neovim, error list is populated after opening definition:

![image](https://user-images.githubusercontent.com/301015/235890982-f975872d-10d4-454f-86d5-8795745b821b.png)

And not cleared after closing definition:

![image](https://user-images.githubusercontent.com/301015/235891145-ee9e97b8-26c2-48e5-99db-2e7223b41fe4.png)

**Comment by glepnir** [comment] 2023-05-03 10:45
vscode use pylance it's not open souce server. pyright is pyright ! and as i said currently lspconfig will check the server support `workspaceFolders` or not . if server not support lspconfig will spawn a new server instance. I most want to how vscode handle rust_analyzer 

ref https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#workspace_workspaceFolders

**Comment by glepnir** [comment] 2023-05-05 08:49
I think I know what the problem is . in vim/neovim we don't have workspace. as default should one nvim instance is a workspace. all project opened should reuse the active server . in vim-lsp it provide a workspace_config field. we should provide a command to make user  We should have provided a simulated workspace table. When the user wants the project to run in a new workspace, manually use a command to add it to the workspace and then check whether the server supports the workspaceFolder feature. If support reuse server send workspace/didchangeworkspacefolder notify otherwise start new server. The logic that currently checks to start the server is not correct ..

**Comment by ten3roberts** [comment] 2023-05-19 07:13
What exactly is a *workspace* in this case?

What would be the way forward for this, because I find myself having to restart neovim if I do `gd` on a library symbol because it will spend a longer time running clippy on the deps, and then clutter the diagnostics with errors (e.g due to features not being enabled or use of unstable library features if in stdlib)

Thanks for the help

**Comment by glepnir** [comment] 2023-05-23 06:44
update the latest version rust_analyzer and test with  definition i can't reproduce this .

**Comment by harrisonmg** [comment] 2023-05-23 19:35
managed to reproduce with version 2023-05-22

**Comment by glepnir** [comment] 2023-05-26 12:48
a hack is  like this .. ..
```lua
    root_dir = function(fname)
      return vim.loop.cwd()
    end,
```

**Comment by glepnir** [comment] 2023-05-27 05:12
The workspace of vscode does not exist in neovim. It is also not possible to simply set a workspace for each root. This is wrong behavior. So I implemented the concept of a workspace in lspconfig. The way it works is. You can create multiple worksapce. A default space is automatically created when the first project is opened. If you don't change the workspace. All open projects will belong to the default space. When you open the project after changing the workspace shown, it will check whether the server supports the workspace_folder feature. Send didchangeworkspacefolder notification if supported. Re-use the server. Otherwise a new server instance will be started. 

for this issue . now it works like this  
1. open `helloword` project now lspconfig will create a `default` workspace. 
2. run `go to definition` it open file which in sysroot. but it still in default workspace . so reuse client and don't send notify 
  even the `rust_analyzer` now support `workspaceFodler`. 
3. now it don't show any diagnostic

![Untitled](https://github.com/neovim/nvim-lspconfig/assets/41671631/4856c747-9257-4236-818b-378ca00ac28d)

**Closed** 2023-06-03 07:08 UTC
Labels: enhancement

**Comment by ten3roberts** [comment] 2023-06-27 10:06
It seems as I mayhaps missed something.

`goto definition` to a library like `std` still produced thousands of diagnostics which remain even after closing any buffer inside `std`?

Thanks for your help so far ❤️

**Comment by glepnir** [comment] 2023-06-27 10:16
with latest version ?  when i navigate to `local/share/rustup/toolchains/stable-x86_64-apple-darwin/lib/rustlib/src/rust/libra│
ry/std/src/lib.rs `  my `RUSTUP` env path . I didn't get any diagnostic.  provide reproduce step .

**Comment by ten3roberts** [comment] 2023-06-27 11:15
lspconfig:
```
    ● nvim-lspconfig 21.77ms   mason.nvim
        dir    /Users/teiroberts/.local/share/nvim/lazy/nvim-lspconfig
        url    https://github.com/neovim/nvim-lspconfig
        branch master
        commit b6b34b9
        readme README.md
        help   |lspconfig.txt|
        help   |lspconfig-all|
```
rust-analyzer
```
    ◍ rust-analyzer rust_analyzer
      rust-analyzer is an implementation of the Language Server Protocol for the
      Rust programming language. It provides features like completion and goto
      definition for many code editors, including VS Code, Emacs and Vim.
      
      
      installed version 2023-06-26                                 
      homepage          https://github.com/rust-lang/rust-analyzer 
      languages         Rust                                       
      categories        LSP                                        
      executables       rust-analyzer                              
```

Steps to reproduce:

`lua vim.lsp.buf.definition()`
on
```
std::net::IpAddr
```

This navigates to `/Users/teiroberts/.rustup/toolchains/stable-aarch64-apple-darwin/lib/rustlib/src/rust/library/std/src/net/mod.rs`

`fidget.nvim` shows that rust-analyzer is indexing.

Wait until it is done indexing

Go to the previous buffer (your source code) and delete the *std* buffer using telescope buffers.

```lua
vim.diagnostic.setqflist()
```

![Screenshot 2023-06-27 at 13 14 00](https://github.com/neovim/nvim-lspconfig/assets/25723553/d35c78f6-add1-457b-b1b4-73336af80b1e)

What do you use to view all the diagnostics?

**Comment by ten3roberts** [comment] 2023-06-27 11:23
I may add that this also occurs on my other machines running Linux, so it is not mac specific. All latest versions

**Comment by glepnir** [comment] 2023-06-27 11:52
I only get main.rs . source file no diangositcs 

![image](https://github.com/neovim/nvim-lspconfig/assets/41671631/f5d51d0a-1594-47b8-8743-eff58eaf930a)

**Comment by ten3roberts** [comment] 2023-06-27 12:22
Removing `rust-tools` solves the issue.

Thanks for implementing the feature, now that I can make use of it is very useful.

I've been on and off rust-tools since it has some issues, but also useful things such as `:RustRunnables` but I have since moved that into another plugin, so I think I can entirely move away from rust-tools.

Thanks for your time 👍

**Comment by ten3roberts** [comment] 2023-06-27 12:37
Wow, so it wasn't just placebo. Amazing.

No more mini-hiccups with `goto-definitions`, something which I didn't even know was caused by lsp-config. Thought it was file loading.

❤️

**Comment by glepnir** [comment] 2023-06-27 12:39
no problem then enjoy :)

**Comment by IceSentry** [comment] 2024-10-28 19:06
I'm confused. This thread seems to indicate the issue doesn't exist anymore, but I'm still having this exact issue. I've been trying to fix it for over a week at this point with still no clue why it's doing this. I only started using neovim recently and all I used is the default config from kickstart.nvim. Whenever I open a file that is from a dependency and not in the CWD it starts running a cargo check. I've resorted to using `autostart = false` and start it manually. When I use `:LspStart` at the root of a rust project everything works fine and it doesn't try to run cargo check outside of the cwd but if I let autostart do it's thing then it tries to run cargo check in other files that I definitely don't want ti to.

**Comment by glepnir** [comment] 2024-10-29 08:29
@IceSentry  open an new issue with a minimal init file that without **any** plugin.

**Comment by ten3roberts** [comment] 2024-10-30 11:10
> @IceSentry  open an new issue with a minimal init file that without **any** plugin and clear reproduce step.

Thank you

Haven't noticed this to be much of an issue myself, not that I've thought of it

`gd` works well into both submodules and registry crates, using it in a project with nontrivial feature flags.

IIRC, rust tools was causing issues as it overrode the setup roots function, but haven't used that crate in some time
