### ISSUE TITLE
Rust analyzer going crazy with indexing causing lag

### ISSUE THREAD

**Issue by jacksonludwig** [neovim/nvim-lspconfig#395] opened 2020-11-05 17:35 UTC
- `nvim --version`: latest nightly
- nvim-lsp version(commit hash): 60133c4
- `:checkhealth` all checks say `OK`
- What language server(If the problem is related to a specific language server): rust analyzer
- Operating system/version: arch latest version
- Terminal name/version: alacritty
- `$TERM`: alacritty

### How to reproduce the problem from neovim startup
Go to a rust project (preferably one of a larger size that requires more work to index) and type/hold down a key to watch lag. Or use some method to view rust_analyzer's activity and see that it is indexing after every character is typed.

I do not encounter this issue when using coc + coc_rust_anaylzer

**Comment by lithammer** [comment] 2020-11-05 19:57
Are you using https://github.com/nvim-lua/completion-nvim as well?

**Comment by lithammer** [comment] 2020-11-05 19:59
If so, it might be related to https://github.com/nvim-lua/completion-nvim/issues/203 and/or https://github.com/neovim/neovim/issues/13049.

**Comment by ludwj61** [comment] 2020-11-06 02:15
Yes I do use it, I will try without completion-nvim and see if there's a difference, thanks.

**Comment by Fanto94** [comment] 2020-11-06 11:14
I've had the exact same problem with the last version of rust-analyzer and your same setup, and i solved downgrading it, but i haven't checked if it works with coc

**Comment by lithammer** [comment] 2020-11-06 11:41
I've actually experienced this myself. Similar to @Fanto94, it started to happen with one of the recent versions of rust-analyzer. It's especially evident if paired with [lsp-status.nvim](https://github.com/nvim-lua/lsp-status.nvim) because the statusline flickers with indexing messages on every keypress in insert mode.

**Comment by ludwj61** [comment] 2020-11-06 15:24
So, I see it indexing on type with coc as well, but there still isn't any lag. It does lag though, with built in lsp regardless if I have completion-nvim or not.

It might be partially rust analyzer's fault and partially built in lsp not handling it well.

**Comment by LesnyRumcajs** [comment] 2020-12-11 10:19
@lithammer Were you able to find a workaround for this? I updated today my plugins and this `indexing` window is popping for every key press in Insert.

**Comment by lithammer** [comment] 2020-12-11 11:04
Unfortunately not. It's unclear to me if it's a Neovim LSP, lsp-status.nvim issue or rust-analyzer issue. But for example if I open a project with VS Code the statusbar shows a constantly spinning cogwheel with the message "Starting".

<img width="153" alt="Screenshot 2020-12-11 at 11 42 45" src="https://user-images.githubusercontent.com/177685/101894123-ffab6f80-3ba5-11eb-815c-ff8bd418984b.png">

It might just be an issue with the vscode-rust plugin, but almost makes it sound like it doesn't 100% finish the startup phase?? On the other hand, VS Code isn't flickering with "Indexing ..." messages when typing. But that might just be due some debouncing and/or buffering of the progress messages.

But given that the problem started by an upgrade of rust-analyzer, I suspect maybe an issue should be raised on their issue tracker as well.

Here's a gif of the problem:

![Dec-11-2020 12-02-38](https://user-images.githubusercontent.com/177685/101896204-e821b600-3ba8-11eb-8940-39dcd05bc90e.gif)

**Comment by LesnyRumcajs** [comment] 2020-12-11 12:20
@lithammer Thanks for the reply.

I had an even more annoying constantly popping floating window with this indexing. I got rid of it by rolling back the coc.nvim update to 806ce47583d66d0b574a3c993526033971e700cf.

**Comment by etrnal70** [comment] 2020-12-15 06:07
Anybody got a clue for this ? Large project are extremely slow on my end and it's even barely usable

**Comment by kid** [comment] 2020-12-20 11:28
I have been experiencing slowdowns as well, disabling `lsp-status` seems to have resolved them, Don't know if that's because of `lsp-status` or how it's called from `vim-airline` in my case

**Comment by mjlbach** [comment] 2020-12-30 00:23
I'm going to close this as this seems to be an issue with lsp-status and rust-analyzer rather than how we are initializing rust-analyzer in this repository.

**Closed by mjlbach** 2020-12-30 00:23 UTC
Labels: bug

**Comment by onsails** [comment] 2021-01-23 18:15
> I have been experiencing slowdowns as well, disabling `lsp-status` seems to have resolved them, Don't know if that's because of `lsp-status` or how it's called from `vim-airline` in my case

I can confirm this problem is actual with lualine.nvim combined with lsp-status.
I've created an issue in lsp-status.
