### ISSUE TITLE
Commit fe88eade4ab50fca9ace99205cad1d91645ed9e8 breaks pyright and ruff

### ISSUE THREAD

**Issue by danpascu** [neovim/nvim-lspconfig#3456] opened 2024-11-26 08:35 UTC
### Description

I'm using the plugin for python with pyright and ruff as language servers. This morning after I updated nvim-lspconfig I noticed things behaving weirdly. Checking the health of the plugin showed two instances of both ruff and pyright running in the initial buffer that was entered after restoring the session. Keyboard shortcuts for prev-symbol (`[[`) didn't work anymore and the shortcut for the next-symbol (`]]`) jumped to weird positions, like from a symbol (class name) jumped to the next class keyword.

At some point after changing buffers and restarting nvim a couple of times I noticed I had 3-4 copies of each language server running and keyboard shortcuts became even more broken. The keyboard shortcut for the previous-symbol deleted a range of text and replaced it with some random pasted content.

This only seems to apply to the first buffer entered after starting nvim and restoring the session. The other buffers I switch to only seem to have a single copy of the language server running for them and they don't exhibit keyboard shortcut problems.

![Image](https://github.com/user-attachments/assets/0da6e667-1dc1-445b-a938-a0591cad6682)

I reverted fe88eade4ab50fca9ace99205cad1d91645ed9e8 and things went back to normal.

**Comment by danpascu** [comment] 2024-11-26 08:51
I should note this doesn't only happen when restoring the previous session. It applies to the first opened buffer, be that from restoring the last session, starting nvim with a file argument or starting nvim and then loading a file.

**Comment by glepnir** [comment] 2024-11-26 08:52
If the server does not support workspaceFolder,should not reuse the existing server. Provide complete minimal reproduction steps. If it is caused by session, then it should be the issue I raised in the previous refactored PR.

**Comment by danpascu** [comment] 2024-11-26 09:08
Maybe it shouldn't reuse servers, but that's not what I see. In the screenshot I attached you can see that buffers 4, 7 and 11 share one copy of the servers and in addition buffer 7 has another copy for each of the servers. Buffer 7 having the 2 copies for each of the server is what causes the problems with the keyboard shortcuts. Buffer 7 is the buffer that was opened first.

Something is obviously wrong since it starts two copies for each language server in the first buffer.

**Comment by glepnir** [comment] 2024-11-26 09:14
> . Provide complete minimal reproduction steps. 

please

**Comment by danpascu** [comment] 2024-11-26 10:19
I'm not sure what qualifies as minimal reproduction steps. I use LazyVim to manage my configuration. If I provide you with the stripped down nvim config folder where I remove all other settings and just leave in the lspconfig settings, is that good enough?

**Comment by glepnir** [comment] 2024-11-26 10:54
I can reproduce with start neovim from a session file .

**Comment by danpascu** [comment] 2024-11-26 11:18
Same thing happens if there is no session involved. If I start nvim like `nvim file.py` or I start nvim and then open a file without restoring any session the same thing happens. I always get duplicate language server instances on the first buffer.

**Comment by glepnir** [comment] 2024-11-26 11:19
I have revert. but it still have another probelm so i will close this issue and open new issue.

**Closed by glepnir** 2024-11-26 11:19 UTC
Labels: bug
