### ISSUE TITLE
Texlab and Efm together causes error when calling `TexlabBuild`.

### ISSUE THREAD

**Issue by riazufila** [neovim/nvim-lspconfig#1258] opened 2021-09-13 12:59 UTC
### Description

When calling `TexlabBuild`, error `Error executing vim.schedule lua callback: ...ack/packer/start/nvim-lspconfig/lua/lspconfig/texlab.lua:30: RPC[Error] code_name = MethodNotFo und, message = "method not supported: textDocument/build` appears. Then, the build will complete as it should. I opened an issue at `latex-lsp/texlab` and they mentioned that this is an issue with lspconfig instead.

### Neovim version

NVIM v0.6.0-dev+262-g643cb8a6e
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3

### Nvim-lspconfig version

974d15fa2809dff691d6a50a6759bf2c8bf39b4a

### Operating system and version

Arch Linux x64

### Affected language servers

texlab

### Steps to reproduce

1. Setup packer and install nvim-lspconfig.
2. Install and start both efm and texlab.

### Actual behavior

`Error executing vim.schedule lua callback: ...ack/packer/start/nvim-lspconfig/lua/lspconfig/texlab.lua:30: RPC[Error] code_name = MethodNotFo und, message = "method not supported: textDocument/build` appears then build completes.

### Expected behavior

Build complete without errors.

### Minimal config

```Lua
vim.cmd([[set runtimepath=$VIMRUNTIME]])
vim.cmd([[set packpath=/tmp/nvim/site]])

local package_root = "/tmp/nvim/site/pack"
local install_path = package_root .. "/packer/start/packer.nvim"

local function load_plugins()
	require("packer").startup({
		{
			"wbthomason/packer.nvim",
			"neovim/nvim-lspconfig",
		},
		config = {
			package_root = package_root,
			compile_path = install_path .. "/plugin/packer_compiled.lua",
		},
	})
end

_G.load_config = function()
	vim.lsp.set_log_level("trace")
	local nvim_lsp = require("lspconfig")
	local on_attach = function(_, bufnr)
		if _.name ~= "efm" then
			_.resolved_capabilities.document_formatting = false
		end

		local function buf_set_keymap(...)
			vim.api.nvim_buf_set_keymap(bufnr, ...)
		end
		local function buf_set_option(...)
			vim.api.nvim_buf_set_option(bufnr, ...)
		end

		buf_set_option("omnifunc", "v:lua.vim.lsp.omnifunc")

		-- Mappings.
		local opts = { noremap = true, silent = true }
		buf_set_keymap("n", "gD", "<Cmd>lua vim.lsp.buf.declaration()<CR>", opts)
		buf_set_keymap("n", "gd", "<Cmd>lua vim.lsp.buf.definition()<CR>", opts)
		buf_set_keymap("n", "K", "<Cmd>lua vim.lsp.buf.hover()<CR>", opts)
		buf_set_keymap("n", "gi", "<cmd>lua vim.lsp.buf.implementation()<CR>", opts)
		buf_set_keymap("n", "<C-k>", "<cmd>lua vim.lsp.buf.signature_help()<CR>", opts)
		buf_set_keymap("n", "<space>wa", "<cmd>lua vim.lsp.buf.add_workspace_folder()<CR>", opts)
		buf_set_keymap("n", "<space>wr", "<cmd>lua vim.lsp.buf.remove_workspace_folder()<CR>", opts)
		buf_set_keymap("n", "<space>wl", "<cmd>lua print(vim.inspect(vim.lsp.buf.list_workspace_folders()))<CR>", opts)
		buf_set_keymap("n", "<space>D", "<cmd>lua vim.lsp.buf.type_definition()<CR>", opts)
		buf_set_keymap("n", "<space>rn", "<cmd>lua vim.lsp.buf.rename()<CR>", opts)
		buf_set_keymap("n", "gr", "<cmd>lua vim.lsp.buf.references()<CR>", opts)
		buf_set_keymap("n", "<space>e", "<cmd>lua vim.lsp.diagnostic.show_line_diagnostics()<CR>", opts)
		buf_set_keymap("n", "[d", "<cmd>lua vim.lsp.diagnostic.goto_prev()<CR>", opts)
		buf_set_keymap("n", "]d", "<cmd>lua vim.lsp.diagnostic.goto_next()<CR>", opts)
		buf_set_keymap("n", "<space>q", "<cmd>lua vim.lsp.diagnostic.set_loclist()<CR>", opts)
	end

	-- Add the server that troubles you here
	nvim_lsp.efm.setup({
		on_attach = on_attach,
		init_options = {
			documentFormatting = true,
		},
	})

	nvim_lsp.texlab.setup({
		on_attach = on_attach,
	})
end

if vim.fn.isdirectory(install_path) == 0 then
	vim.fn.system({ "git", "clone", "https://github.com/wbthomason/packer.nvim", install_path })
	load_plugins()
	require("packer").sync()
	vim.cmd([[autocmd User PackerComplete ++once lua load_config()]])
else
	load_plugins()
	require("packer").sync()
	_G.load_config()
end
```
```


### Health check

health#lspconfig#check
========================================================================
## Checking language server protocol configuration
  - INFO: efm: configuration checked.
  - INFO: texlab: configuration checked.


### LSP log

https://gist.github.com/riazufila/fb5a4b908b044bcd89071ff176a39e63

**Comment by clason** [comment] 2021-09-13 13:01
As I mentioned on the texlab issue https://github.com/latex-lsp/texlab/issues/485, the error comes from `efm` since the request is sent to all attached servers. (It goes away if `efm` is removed.)

**Comment by mjlbach** [comment] 2021-09-13 21:46
Duplicate of https://github.com/neovim/neovim/issues/15174

**Closed by mjlbach** 2021-09-13 21:46 UTC
Labels: bug

**Comment by tiagovla** [comment] 2021-11-07 22:03
#15174 was closed but efm+texlab still don't work together.

**Comment by mjlbach** [comment] 2021-11-07 22:54
Are you on the latest nightly?

**Comment by tiagovla** [comment] 2021-11-12 21:59
I built from master today and it still gives me this:

```
Error executing vim.schedule lua callback: .../pack/packer/opt/nvim-lspconfig/lua/lsp
config/texlab.lua:30: RPC[Error] code_name = MethodNotFound, message = "method not su
pported: textDocument/build"
stack traceback:
        [C]: in function 'error'
        .../pack/packer/opt/nvim-lspconfig/lua/lspconfig/texlab.lua:30: in function '
handler'
        /usr/local/share/nvim/runtime/lua/vim/lsp.lua:927: in function 'cb'
        vim.lua:285: in function <vim.lua:285>
```

I'm trying to get ``efm`` and ``texlab`` to work together because ``texlab`` is not working properly with ``luasnip`` https://github.com/latex-lsp/texlab/issues/503.
