### ISSUE TITLE
Cursor position returned to top line when applying formatting (rust-analyzer, dartls)

### ISSUE THREAD

**Issue by dialtone** [neovim/nvim-lspconfig#465] opened 2020-12-19 18:55 UTC
- `nvim --version`:

```
NVIM v0.5.0-dev+nightly-243-gf12bbf62c
Build type: Release
LuaJIT 2.1.0-beta3
Compilation: /usr/bin/clang -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -DNDEBUG -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fno-common -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -DMIN_LOG_LEVEL=3 -I/tmp/neovim-20201219-5490-15mrudw/build/config -I/tmp/neovim-20201219-5490-15mrudw/src -I/usr/local/include -I/tmp/neovim-20201219-5490-15mrudw/deps-build/include -I/Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/usr/include -I/usr/local/opt/gettext/include -I/tmp/neovim-20201219-5490-15mrudw/build/src/nvim/auto -I/tmp/neovim-20201219-5490-15mrudw/build/include
Compiled by dialtone@pasocon

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/local/Cellar/neovim/HEAD-f12bbf6/share/nvim"

Run :checkhealth for more info
```

- nvim-lsp version(commit hash):
`1e4a963ba4d00d559247b5fca827142958d4dbdf`

- `:checkhealth` result
```

health#lspconfig#check
========================================================================
## Checking language server protocol configuration
  - ERROR: jsonls: The given command "vscode-json-languageserver" is not executable.
  - INFO: terraformls: configuration checked.
  - ERROR: html: The given command "html-languageserver" is not executable.
  - INFO: gopls: configuration checked.
  - INFO: rust_analyzer: configuration checked.
  - INFO: clangd: configuration checked.

health#completion_nvim#check
========================================================================
## general
  - OK: neovim version is supported

## completion source
  - OK: all completion source are valid

## snippet source
  - INFO: You haven't setup any snippet source.

health#nvim#check
========================================================================
## Configuration
  - OK: no issues found

## Performance
  - OK: Build type: Release

## Remote Plugins
  - OK: Up to date

## terminal
  - INFO: key_backspace (kbs) terminfo entry: key_backspace=^H
  - INFO: key_dc (kdch1) terminfo entry: key_dc=\E[3~
  - INFO: $TERM_PROGRAM='Alacritty.app'
  - INFO: $COLORTERM='truecolor'

## tmux
  - OK: escape-time: 0
  - INFO: Checking stuff
  - OK: focus-events: on
  - INFO: $TERM: xterm-256color
  - ERROR: $TERM should be "screen-256color" or "tmux-256color" in tmux. Colors might look wrong.
    - ADVICE:
      - Set default-terminal in ~/.tmux.conf:
          set-option -g default-terminal "screen-256color"
      - https://github.com/neovim/neovim/wiki/FAQ

health#provider#check
========================================================================
## Clipboard (optional)
  - OK: Clipboard tool found: pbcopy

## Python 2 provider (optional)
  - INFO: `g:python_host_prog` is not set.  Searching for python2 in the environment.
  - INFO: Multiple python2 executables found.  Set `g:python_host_prog` to avoid surprises.
  - INFO: Executable: /usr/local/bin/python2
  - INFO: Other python executable: /usr/bin/python2
  - INFO: Python version: 2.7.17
  - INFO: pynvim version: 0.4.2
  - OK: Latest pynvim is installed.

## Python 3 provider (optional)
  - INFO: `g:python3_host_prog` is not set.  Searching for python3 in the environment.
  - INFO: Multiple python3 executables found.  Set `g:python3_host_prog` to avoid surprises.
  - INFO: Executable: /usr/local/bin/python3
  - INFO: Other python executable: /usr/bin/python3
  - INFO: Python version: 3.9.1
  - INFO: pynvim version: 0.4.2
  - OK: Latest pynvim is installed.

## Python virtualenv
  - OK: no $VIRTUAL_ENV

## Ruby provider (optional)
  - INFO: Ruby: ruby 2.5.3p105 (2018-10-18 revision 65156) [x86_64-darwin18]
  - WARNING: `neovim-ruby-host` not found.
    - ADVICE:
      - Run `gem install neovim` to ensure the neovim RubyGem is installed.
      - Run `gem environment` to ensure the gem bin directory is in $PATH.
      - If you are using rvm/rbenv/chruby, try "rehashing".
      - See :help |g:ruby_host_prog| for non-standard gem installations.

## Node.js provider (optional)
  - INFO: Node.js: v15.3.0
  - WARNING: Missing "neovim" npm (or yarn) package.
    - ADVICE:
      - Run in shell: npm install -g neovim
      - Run in shell (if you use yarn): yarn global add neovim

## Perl provider (optional)
  - ERROR: perl provider error:
    - ADVICE:
      - Perl version is too old, 5.22+ required
```

- What language server(If the problem is related to a specific language server):
```rust-analyzer```
- Operating system/version:
```macOS 10.15.7```
- Terminal name/version:
```alacritty 0.6.0```
- `$TERM`:
```xterm-256color```

### How to reproduce the problem from neovim startup
Clone https://github.com/dialtone/aoc and open the file
https://github.com/dialtone/aoc/blob/main/src/solutions/year2020/day19.rs

If you add new lines inside the curly brackets of `fn day192() {}` and then save to format the cursor should go at the top of the buffer.

have the standard documented lsp setup for rust-analyzer and setup as well either:
on attach:
```
    vim.api.nvim_command("au BufWritePre <buffer> lua vim.lsp.buf.formatting_sync(nil, 1000)")
```
or 
```
autocmd BufWritePre *.rs lua vim.lsp.buf.formatting_sync(nil, 1000)
```
In looking to enable format on save.

### Actual behaviour
Whenver some actual formatting happens, particularly moving parenthesis, the cursor is sent to the top of the buffer.

### Expected behaviour
Cursor stays where it is instead of going up to.

**Comment by dialtone** [comment] 2020-12-19 23:02
By using:

```
lua <<EOF
function format_rust()
    local lineno = vim.api.nvim_win_get_cursor(0)
    vim.lsp.buf.formatting_sync(nil, 1000)
    vim.api.nvim_win_set_cursor(0, lineno)
end
EOF
autocmd BufWritePre *.rs lua format_rust()
```

the cursor stays in its location and doesn't jump around although this is obviously not optimal.

**Comment by mjlbach** [comment] 2020-12-20 09:25
Can you reproduce this on other language servers? The vim.lsp api is not implemented in this repository, but in neovim core and this bug should likely be filed there if this isn't the desired behavior. Here is where the formatting_sync is implemented.

https://github.com/neovim/neovim/blob/9539d46bb120ac135f390600ea6f82112478ef1d/runtime/lua/vim/lsp/buf.lua#L137-L145

I would assume apply_edits is what is at fault

**Comment by dialtone** [comment] 2020-12-22 00:02
No wasn't able to repro on other LSP. Tried with gopls but it worked fine there. only in rust for me, maybe weird rust_analyzer interaction.

**Comment by mjlbach** [comment] 2021-01-03 16:16
I'm not able to reproduce this, it seems to be working fine for me. Can you try updating rust analyzer?

Uploading Screen Recording 2021-01-03 at 8.15.10 AM.mov…

**Comment by akinsho** [comment] 2021-01-03 17:55
Just chiming in here, I've also noted this using `dartls` there's actually a workaround people have recommended on [reddit](https://www.reddit.com/r/neovim/comments/k91a3a/neovim_lsp_format_cause_cursor_moved_to_the/), I believe it depends on if the position your cursor was on would be invalid once the formatting is completed, and if so it gets put at the top.

Definitely one for upstream though, I just did a very brief search and don't think anyone has actually raised this yet, or maybe it's labelled something a little less explicit

**Comment by mjlbach** [comment] 2021-01-03 18:00
Yeah it would be very helpful to get a test-case that reproduces, that we could compare across clients. I could imagine this being a rust-analyzer/dartls specific thing, or an issue with neovim core. Just FYI none of the formatting code is implemented in this repo.

**Comment by akinsho** [comment] 2021-01-03 20:24
![formatting_bug](https://user-images.githubusercontent.com/22454918/103487961-fad28800-4e00-11eb-8a36-faba62216edd.gif)

I'm triggering the `lua vim.lsp.buf.formatting_sync(nil, 1000)` in a `BufWritePre` command

@mjlbach here is gif reproducing the issue. The minimal amount of dart code I extracted to trigger it was
```dart
import 'package:flutter/widgets.dart';

class Navigation {
  final navigator = GlobalKey<NavigatorState>();
  Future<void> navigateAndClearHistory(String route, {Object arguments}) {
    return navigator.currentState.pushNamedAndRemoveUntil(
        route, (Route<dynamic> route) => false,
        arguments: arguments
        ); // <-- cursor placed here
  }
}
```

**Comment by mjlbach** [comment] 2021-01-05 02:28
For dart, I don't think there is anything we can do about this. `vim.lsp.buf.formatting()` just triggers the server to edit tthe document which causes the buffer to refresh. There's no information returned about where the cursor should be, that we could use to intelligently place the cursor.

I don't think the solution listed above is optimal:
```
    local lineno = vim.api.nvim_win_get_cursor(0)
    vim.lsp.buf.formatting_sync(nil, 1000)
    vim.api.nvim_win_set_cursor(0, lineno)
```

If you have a lot of whitespace, then this will place you at a random part of the document after the formatting? Is this what coc is doing? The real solution is an extension to the LSP protocol to return a desired cursor location from the server.

**Comment by mjlbach** [comment] 2021-01-05 03:14
Nvm, I think I have something that will work, making a PR.

**Comment by mjlbach** [comment] 2021-01-05 03:50
This fixes it, but causes a lot of tests to fail:

https://github.com/mjlbach/neovim/commit/5b3ee9cb5de149f1ab729e732910be43bc7680b0

**Comment by dialtone** [comment] 2021-01-05 05:58
Yeah I don't think the workaround I provided is a good solution, it does work as a workaround though while waiting for proper fixes.

**Comment by mjlbach** [comment] 2021-01-05 09:13
I'm going to close this because it's not a buf in formatting, it's a bug in nvim_buf_set_lines which is a more general problem. Once that is fixed, this issue will go away. Since it's implemented in neovim core, I opened the issue there. See: 

https://github.com/neovim/neovim/issues/13691

**Closed** 2021-01-05 09:13 UTC
Labels: bug, needs-repro

**Comment by mjlbach** [comment] 2021-01-05 11:30
See #13692 for the fix

**Comment by akinsho** [comment] 2021-01-05 12:38
Thanks for looking into it @mjlbach 👍🏿

**Comment by mjlbach** [comment] 2021-01-06 22:12
Will (also) will be closed by https://github.com/neovim/neovim/pull/13703

**Comment by craftzdog** [comment] 2021-07-09 06:19
It still happens if you have split panes that have the same file.
The cursor stays at the same position in the current pane, but the cursor moves to top in another pane on save.
My configuration:

```lua
if client.resolved_capabilities.document_formatting then
  vim.api.nvim_command [[augroup Format]]
  vim.api.nvim_command [[autocmd! * <buffer>]]
  vim.api.nvim_command [[autocmd BufWritePre <buffer> lua vim.lsp.buf.formatting_sync(nil, 1000)]]
  vim.api.nvim_command [[augroup END]]
end
```

**Comment by mjlbach** [comment] 2021-07-09 06:21
You can follow https://github.com/neovim/neovim/issues/14645
