### ISSUE TITLE
Julials crashes on file save

### ISSUE THREAD

**Issue by quantum-booty** [neovim/nvim-lspconfig#526] opened 2021-01-04 00:16 UTC
- nvim --version: NVIM v0.5.0-dev+1005-ga1ed941a7
- nvim-lsp version(commit hash): 2558d93e4f047e2b01db8f98bbfaf4c291e743d5
- :checkhealth result
- link to checkhealth: https://hastebin.com/jibodobida.sql
- What language server(If the problem is related to a specific language server): Julia
- Is this problem isolated to this particular language server: Yes
- Operating system/version: Arch
- Terminal name/version: tried on Kitty and Alacritty

### How to reproduce the problem from neovim startup
```au BufNewFile,BufRead *.jl set filetype=julia

call plug#begin('~/.config/nvim/plugged')
Plug 'nvim-lua/completion-nvim'
Plug 'neovim/nvim-lspconfig'
call plug#end()

set updatetime=50
set completeopt+=menuone,noselect,noinsert
set completeopt-=preview
set shortmess+=c

autocmd BufEnter * lua require'completion'.on_attach()

lua <<EOF
require'lspconfig'.julials.setup{}
EOF

lua vim.lsp.set_log_level('error')
" log_path: ~/.local/share/nvim/lsp.log

```
### LSP log
https://hastebin.com/weqetowimi.lua

There are three stages in the error log:
1) when the file is opened: First line in the log.
2) after the language server is fully loaded: From 2nd to the 9th line which ends with this text:
```"[ Info: Received new data from Julia Symbol Server.\n"```
3) save the file which causes the language server to crash: everything after

**Comment by mjlbach** [comment] 2021-01-04 05:37
```
[ ERROR ] 2021-01-04T00:08:58+0000 ] /usr/local/share/nvim/runtime/lua/vim/lsp/rpc.lua:455 ]	"rpc"	"julia"	"stderr"	"ERROR: "
[ ERROR ] 2021-01-04T00:08:59+0000 ] /usr/local/share/nvim/runtime/lua/vim/lsp/rpc.lua:455 ]	"rpc"	"julia"	"stderr"	"MethodError: no method matching send(::JSONRPC.JSONRPCEndpoint, ::JSONRPC.NotificationType{LanguageServer.ShowMessageRequestParams}, ::LanguageServer.ShowMessageParams)\nClosest candidates are:\n  send(::JSONRPC.JSONRPCEndpoint, !Matched::JSONRPC.RequestType{TPARAM,TR}, ::TPARAM) where {TPARAM, TR} at /home/henryw/.julia/packages/JSONRPC/1Kq3H/src/typed.jl:22\n  send(::JSONRPC.JSONRPCEndpoint, ::JSONRPC.NotificationType{TPARAM}, !Matched::TPARAM) where TPARAM at /home/henryw/.julia/packages/JSONRPC/1Kq3H/src/typed.jl:35\nStacktrace:"
[ ERROR ] 2021-01-04T00:08:59+0000 ] /usr/local/share/nvim/runtime/lua/vim/lsp/rpc.lua:455 ]	"rpc"	"julia"	"stderr"	"\n [1] "
[ ERROR ] 2021-01-04T00:09:00+0000 ] /usr/local/share/nvim/runtime/lua/vim/lsp/rpc.lua:455 ]	"rpc"	"julia"	"stderr"	"textDocument_didSave_notification"
[ ERROR ] 2021-01-04T00:09:00+0000 ] /usr/local/share/nvim/runtime/lua/vim/lsp/rpc.lua:455 ]	"rpc"	"julia"	"stderr"	"("
[ ERROR ] 2021-01-04T00:09:00+0000 ] /usr/local/share/nvim/runtime/lua/vim/lsp/rpc.lua:455 ]	"rpc"	"julia"	"stderr"	"::"
[ ERROR ] 2021-01-04T00:09:00+0000 ] /usr/local/share/nvim/runtime/lua/vim/lsp/rpc.lua:455 ]	"rpc"	"julia"	"stderr"	"LanguageServer"
[ ERROR ] 2021-01-04T00:09:00+0000 ] /usr/local/share/nvim/runtime/lua/vim/lsp/rpc.lua:455 ]	"rpc"	"julia"	"stderr"	".DidSaveTextDocumentParams, ::LanguageServerInstance, ::JSONRPC.JSONRPCEndpoint) at "
[ ERROR ] 2021-01-04T00:09:00+0000 ] /usr/local/share/nvim/runtime/lua/vim/lsp/rpc.lua:455 ]	"rpc"	"julia"	"stderr"	"/home/henryw/.julia/packages/LanguageServer/y1ebo/src/requests/textdocument.jl:53\n [2] "
[ ERROR ] 2021-01-04T00:09:00+0000 ] /usr/local/share/nvim/runtime/lua/vim/lsp/rpc.lua:455 ]	"rpc"	"julia"	"stderr"	'(::LanguageServer.var"#121#153"{LanguageServerInstance})(::JSONRPC.JSONRPCEndpoint, ::LanguageServer.'
[ ERROR ] 2021-01-04T00:09:00+0000 ] /usr/local/share/nvim/runtime/lua/vim/lsp/rpc.lua:455 ]	"rpc"	"julia"	"stderr"	"DidSaveTextDocumentParams) at /home/henryw/.julia/packages/LanguageServer/y1ebo/src/languageserverinstance.jl:293\n [3] dispatch_msg(::JSONRPC.JSONRPCEndpoint, ::JSONRPC.MsgDispatcher, ::Dict{String,Any}) at /home/henryw/.julia/packages/JSONRPC/1Kq3H/src/typed.jl:66\n [4] run(::LanguageServerInstance) at /home/henryw/.julia/packages/LanguageServer/y1ebo/src/languageserverinstance.jl:308\n [5] top-level scope at none:12\n"
```

This indicates a problem in symbol server (not julia's language server). We can't do anything about internal julia language server errors, so I would report this upstream.

Furthermore I'm not able to reproduce this, I can save and edit julia files fine. Can you try updating julia-language-server and sending me your snippet? I'm closing this because it's not a bug in neovim, but I'll still help you file a good bug report with julia language server.

**Closed by mjlbach** 2021-01-04 05:37 UTC
Labels: bug

**Comment by quantum-booty** [comment] 2021-01-04 18:02
@mjlbach It still crashes on file save after I've updated nvim, lsp-config,  LanguageServer and SymbolServer packages. I don't think it has anything to do with the code I'm trying to edit becauses it crashes even when I try to save an empty file. I really appreciate your help, thank you so much!
