### ISSUE TITLE
Unclear documentation for how to set a specific option

### ISSUE THREAD

**Issue by unphased** [neovim/nvim-lspconfig#172] opened 2020-03-16 09:44 UTC
I'm trying to use `ccls` with nvim-lsp, and I've gotten as far as it loading up and displaying the same behavior as the default config as seen through coc.nvim. Now, I was just now able to *FINALLY* work out how to get ccls from homebrew functioning for macOS, the issue I was stuck on for months was the need to set 

    "clang": {
      "extraArgs": ["-isystem", "/usr/local/Cellar/llvm/9.0.1/include/c++/v1"]
    },

(thanks to a deep dive into https://github.com/MaskRay/ccls/issues/191)

Now that I have figured this out for coc.nvim in which the LSP config is in a json file, I'm trying to work out how to tell `nvim-lsp` how to set the same config through a Lua heredoc, and I've been failing. So far I've got this: 

```
if has('nvim')
	echo 'nvim_lsp setting up ccls'
	lua vim.lsp.set_log_level("debug")
lua << EOF
	require'nvim_lsp'.ccls.setup{
		initializationOptions = {
			clang = {
				extraArgs = {'-isystem', '/usr/local/Cellar/llvm/9.0.1/include/c++/v1'}
			}
		}
	}
EOF
```

This appears to finally be Lua syntax compatible (sorry... I am a little familiar with Lua, I even integrated it into my own game engine 10 years ago, but I haven't used it since then), and the nvim-lsp log that I located at `~/.local/share/nvim/vim-lsp.log` contains what I set, which indicates that it got parsed, but it also contains the log coming out of `ccls` which clearly indicates that the `extraArgs` are not being set.

So my question is, how can I fix my Lua config for ccls for nvim_lsp to assign this?

Testing with `NVIM v0.5.0-416-g2b00d1d09`, though I'm sure it doesn't matter, I'm just asking about syntax and am pretty sure the nvim here is new enough.

The readme has the option fully documented, but I can't figure out how to specify it successfully.

**Comment by unphased** [comment] 2020-03-16 10:02
Sigh. Well it was easy enough to get it working using a .ccls file, but this is less scalable than global configuration.

**Comment by unphased** [comment] 2020-04-08 00:19
I was able to make the https://github.com/jackguo380/vim-lsp-cxx-highlight plugin work by using this clue from:
https://github.com/neovim/nvim-lsp/issues/70#issuecomment-565237134
for the initialization options. However the ability to set extraArgs is still nowhere to be seen.

**Comment by mjlbach** [comment] 2021-01-04 06:06
Can you provide some more information on how the documentation could be improved? We're providing basic initialization and most common defaults for each server, so if there's a way that this could be clarified for ccls in particular, please let me know.

**Comment by mjlbach** [comment] 2021-01-04 06:54
I'm closing this because it's kind of a duplicate of https://github.com/neovim/nvim-lspconfig/issues/70 in that both made it clear that ccls needed more explicit documentation that all options should be passed via on_init. I have a PR that you can provide feedback on #528

**Closed by mjlbach** 2021-01-04 06:54 UTC
Labels: documentation
