### ISSUE TITLE
Neovim opening multiple instances of OmniSharp

### ISSUE THREAD

**Issue by aqez** [neovim/nvim-lspconfig#1329] opened 2021-10-20 17:27 UTC
### Description

Neovim opens multiple OmniSharp instances every time. After opening the first file, OmniSharp will load up with the correct source directory specified `-s root/directory` but then upon opening a second file in this same directory tree, another instance of OmniSharp will be started with the exact same directory. It also appends an additional `-s root/directory/` to the end of the original instance as well. Further files open in the originally opened instance, such that one instance handles everything except the second file that was opened. 

### Neovim version

$ nvim --version
NVIM v0.5.0
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3

(I have also tried nightly)

### Nvim-lspconfig version

7f902f952944aa708c78138f6536c0dc55aec3a2

### Operating system and version

Windows 10 (does not appear to happen on my linux machine)

### Affected language servers

omnisharp

### Steps to reproduce

So.. repro steps:

1. Have a solution with a structure similar to this:
    >$ tree
    yo
    ├── Project1
    │   ├── Program.cs
    │   └── Project1.csproj
    ├── Project2
    │   ├── Program.cs
    │   └── Project2.csproj
    └── yo.sln

2. Open neovim in parent directory (`yo/` in this example)
3. Open Project1/Program.cs
   - Wait for language server to open and load, you can check with `:LspInfo`
   - ![image](https://user-images.githubusercontent.com/8353400/138138935-1b685a70-a801-49bb-8bd5-f727a5b7b4d8.png)
4. Open Project2/Program.cs
   - Wait for **second** language server to open and load. 
   - ![image](https://user-images.githubusercontent.com/8353400/138139082-eae8634f-2028-4d7b-b67b-f8a256c647f3.png)

Further files that are opened after this point are associated with the first language server, and the buffers are correctly shown under it. You'll also notice that each of the language servers also has **two** `-s` arguments provided now, even though they originally had one. 

![image](https://user-images.githubusercontent.com/8353400/138139400-632b12ad-3fde-45b6-941a-dd5fe856de38.png)

These two additional buffers (15 and 17) are under each of the different project folders respectively, so it does not have to do with which folder they are in. So.. just to recap:

- Buffer 1 opened the original omnisharp instance
- Buffer 2 opened a new one
- Buffer 15 didn't open a new one and was just associated with the original instance (along with buffer 1)
- Same for buffer 17

### Actual behavior

Multiple omnisharp servers are opened.

### Expected behavior

One omnisharp server is opened.

### Minimal config

```Lua
vim.cmd [[set runtimepath=$VIMRUNTIME]]
vim.cmd [[set packpath=/tmp/nvim/site]]

local package_root = '/tmp/nvim/site/pack'
local install_path = package_root .. '/packer/start/packer.nvim'

local function load_plugins()
  require('packer').startup {
    {
      'wbthomason/packer.nvim',
      'neovim/nvim-lspconfig',
    },
    config = {
      package_root = package_root,
      compile_path = install_path .. '/plugin/packer_compiled.lua',
    },
  }
end

_G.load_config = function()
  vim.lsp.set_log_level 'trace'
  if vim.fn.has 'nvim-0.5.1' == 1 then
    require('vim.lsp.log').set_format_func(vim.inspect)
  end
  local nvim_lsp = require 'lspconfig'
  local on_attach = function(_, bufnr)
    local function buf_set_keymap(...)
      vim.api.nvim_buf_set_keymap(bufnr, ...)
    end
    local function buf_set_option(...)
      vim.api.nvim_buf_set_option(bufnr, ...)
    end

    buf_set_option('omnifunc', 'v:lua.vim.lsp.omnifunc')

    -- Mappings.
    local opts = { noremap = true, silent = true }
    buf_set_keymap('n', 'gD', '<Cmd>lua vim.lsp.buf.declaration()<CR>', opts)
    buf_set_keymap('n', 'gd', '<Cmd>lua vim.lsp.buf.definition()<CR>', opts)
    buf_set_keymap('n', 'K', '<Cmd>lua vim.lsp.buf.hover()<CR>', opts)
    buf_set_keymap('n', 'gi', '<cmd>lua vim.lsp.buf.implementation()<CR>', opts)
    buf_set_keymap('n', '<C-k>', '<cmd>lua vim.lsp.buf.signature_help()<CR>', opts)
    buf_set_keymap('n', '<space>wa', '<cmd>lua vim.lsp.buf.add_workspace_folder()<CR>', opts)
    buf_set_keymap('n', '<space>wr', '<cmd>lua vim.lsp.buf.remove_workspace_folder()<CR>', opts)
    buf_set_keymap('n', '<space>wl', '<cmd>lua print(vim.inspect(vim.lsp.buf.list_workspace_folders()))<CR>', opts)
    buf_set_keymap('n', '<space>D', '<cmd>lua vim.lsp.buf.type_definition()<CR>', opts)
    buf_set_keymap('n', '<space>rn', '<cmd>lua vim.lsp.buf.rename()<CR>', opts)
    buf_set_keymap('n', 'gr', '<cmd>lua vim.lsp.buf.references()<CR>', opts)
    buf_set_keymap('n', '<space>e', '<cmd>lua vim.lsp.diagnostic.show_line_diagnostics()<CR>', opts)
    buf_set_keymap('n', '[d', '<cmd>lua vim.lsp.diagnostic.goto_prev()<CR>', opts)
    buf_set_keymap('n', ']d', '<cmd>lua vim.lsp.diagnostic.goto_next()<CR>', opts)
    buf_set_keymap('n', '<space>q', '<cmd>lua vim.lsp.diagnostic.set_loclist()<CR>', opts)
  end

  -- Add the server that troubles you here
  local name = 'omnisharp'
  local pid = vim.fn.getpid()
  local cmd = { 'C:\\omnisharp_stdio\\OmniSharp.exe', "--languageserver", "--hostpid", tostring(pid) } -- needed for elixirls, omnisharp, sumneko_lua
  if not name then
    print 'You have not defined a server name, please edit minimal_init.lua'
  end
  if not nvim_lsp[name].document_config.default_config.cmd and not cmd then
    print [[You have not defined a server default cmd for a server
      that requires it please edit minimal_init.lua]]
  end

  nvim_lsp[name].setup {
    cmd = cmd,
    on_attach = on_attach,
  }

  print [[You can find your log at $HOME/.cache/nvim/lsp.log. Please paste in a github issue under a details tag as described in the issue template.]]
end

if vim.fn.isdirectory(install_path) == 0 then
  vim.fn.system { 'git', 'clone', 'https://github.com/wbthomason/packer.nvim', install_path }
  load_plugins()
  require('packer').sync()
  vim.cmd [[autocmd User PackerComplete ++once lua load_config()]]
else
  load_plugins()
  require('packer').sync()
  _G.load_config()
end
```

### Health check
```
health#lspconfig#check
========================================================================
## Checking language server protocol configuration
  - INFO: omnisharp: configuration checked.
```

### LSP log

https://gist.github.com/aqez/9a5fe0e925e1320a97211eed5ea94901

**Comment by mjlbach** [comment] 2021-10-30 21:16
Dupe of #1168 (just closing this issue, going to look at your PR later)

**Closed by mjlbach** 2021-10-30 21:16 UTC
Labels: bug
