### ISSUE TITLE
python lsp error on 0.5.1

### ISSUE THREAD

**Issue by DavidePatria** [neovim/nvim-lspconfig#1361] opened 2021-11-01 10:49 UTC
### Description

when opening a python file with either pylsp or pylsp configured neovim prints an error:
`error detected while processing FileType autocommands for "python":
E5108: Errorexecuting lua /usr/share/nvim/runtime/lua/vim/uri.lua:43: attempt to call upvalue 'tohex' (a nil value).
the same configuration actually works using neovim nightly appimage.

works fine woth cland.

### Neovim version

NVIM v0.5.1
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3
Compilation: /usr/bin/cc -O2 -Wall -D_FORTIFY_SOURCE=2 -fstack-protector-strong -funwind-tables -fasynchronous-unwind-tables -fstack-clash-protection -Werror=return-type -flto=auto -g -fcommon -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -DNVIM_TS_HAS_SET_MATCH_LIMIT -Og -g -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fno-common -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -DMIN_LOG_LEVEL=3 -I/home/abuild/rpmbuild/BUILD/neovim-0.5.1/build/config -I/home/abuild/rpmbuild/BUILD/neovim-0.5.1/src -I/usr/include -I/usr/include/lua5.1 -I/home/abuild/rpmbuild/BUILD/neovim-0.5.1/build/src/nvim/auto -I/home/abuild/rpmbuild/BUILD/neovim-0.5.1/build/include
Compilato da abuild@OBS

Features: +acl +iconv +tui
See ":help feature-compile"

   file vimrc di sistema: "$VIM/sysinit.vim"
         $VIM di riserva: "/usr/share/nvim"

Run :checkhealth for more info

### Nvim-lspconfig version

cb037a0c075171d1084c55f3e59e923e71b2abca

### Operating system and version

opensuse tumbleweed 

### Affected language servers

pyright (system install) pylsp (pip install)

### Steps to reproduce

call plug#begin('~/.config/nvim/plugins')

Plug 'neovim/nvim-lspconfig'

call plug#end()

lua require'lspconfig'.pylsp.setup{}
lua require'lspconfig'.clangd.setup{}

open a python file and get the error above.
I don't have a full lua config, so I used my own minimal init.vim . hope it is enough

### Actual behavior

an error pops up referencing `uri.lua`. actually changing the return value doesn't trigger the error, but the lsp solely attaches without working. 
e.g. putting this at line 42 of uri.lua
```local function percent_encode_char(char)
    return "%25"```
makes the lsp attach, but nothing shows up


### Expected behavior

_No response_

### Minimal config

```Lua
call plug#begin('~/.config/nvim/plugins')

Plug 'neovim/nvim-lspconfig'

call plug#end()

lua require'lspconfig'.pylsp.setup{}
lua require'lspconfig'.clangd.setup{}
```

### Health check

```
health#lspconfig#check
========================================================================
## Checking language server protocol configuration
  - INFO: pylsp: configuration checked.
  - INFO: clangd: configuration checked.

```

### LSP log

https://gist.github.com/DavidePatria/adcec475175b01ccf51f2bd4f002b500

**Comment by mjlbach** [comment] 2021-11-01 16:03
That's an issue for neovim/neovim, however, if the issue is resolved in the nightly then it's already closed, so I would recommend switching to the nightly until 0.6 is released later this month.

**Closed by mjlbach** 2021-11-01 16:03 UTC
Labels: bug

**Comment by DavidePatria** [comment] 2021-11-01 16:05
well, actually it works with whichever version of the appimage I use, even the one available in opensuse repos. I guess it is more related to my system and some errors I'm getting on npm when installing globally
