### ISSUE TITLE
Import failded in vuels

### ISSUE THREAD

**Issue by timsofteng** [neovim/nvim-lspconfig#388] opened 2020-10-27 19:07 UTC
Hello. I got this error when i tried to import file into vue file.

![image](https://user-images.githubusercontent.com/51912173/97349640-63006d00-1898-11eb-8ca4-a2321e1755b1.png)

**Comment by mjlbach** [comment] 2020-12-18 22:13
@timsofteng Do you see this bug in vscode with vuels as well? If so, have you reported upstream?

**Comment by mjlbach** [comment] 2020-12-30 23:07
Closing, Vue seems to be working fine now and I can't reproduce this. Feel free to submit an example project, but even so I feel as though if there is an issue, it's upstream.

**Closed by mjlbach** 2020-12-30 23:07 UTC
Labels: bug
